  import type { Metadata } from "next";
  import { Analytics } from '@vercel/analytics/react';
  import "./globals.css";
  import { ClerkProvider, SignedIn, SignedOut, SignIn, SignInButton, UserButton } from "@clerk/nextjs";
  import Navbar from "./component-custom/bars/navbar";
  import { Toaster } from "@/components/ui/sonner";
 

  export const metadata: Metadata = {
    title: "tripaki",
    description: "Generated by create next app",
  };

 

  export default async function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>)
  {
      
   
    
    return (
    <ClerkProvider 
    signInUrl="/sign-in"
    signUpUrl="/sign-up"
    >
      <html lang="en  " className="bg-[#010038]  ">
        <body
          id="datepicker-portal"
        >
          <Navbar withtripname={false}/>
          {children}
          <Analytics />
        </body>
      </html>
    </ClerkProvider>
    );
  }
