name: Deploy Next.js App to Azure

on:
  push:
    branches: 
      - main # Change this to your deployment branch.(Our branch called main)
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Use the Node.js version required by your project

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the Next.js application
      - name: Build the app
        run: npm run build

      # Step 5: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }} # Set this secret in GitHub
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: '.next' # The build output folder for Next.js (customize if needed)
